### PR TITLE
Add blackhole scan by interval

### LINKED ISSUE #205: Add Blackhole Polling Task (for remote filesystems)
As some people already discovered (https://github.com/piejanssens/premiumizer/issues/85#issuecomment-341991788), the blackhole functionality does not work with remote filesystems like NFS. This is no issue with the watchdir/blackhole functionality, nor in the NFS implementation. It's intended behavior to not send all file system changes to every user who mounted the NFS share as this would result in horrendous traffic.

If the watchdir is enabled, https://github.com/piejanssens/premiumizer/blob/f64641189ade86f08d1a0d57f745af36e6c8d625/premiumizer/premiumizer.py#L1892 gets called one, which starts the watchdog/filesystem obsever. After that, https://github.com/piejanssens/premiumizer/blob/f64641189ade86f08d1a0d57f745af36e6c8d625/premiumizer/premiumizer.py#L1900 walks through all existing files in the directory and fakes the `on_created` event to work through all the files that premiumizer might have missed while being stopped. This is great behavior.

My goal is to use the same functionality in a task that runs every **n** (configurable) seconds, much like the `update` tasks. This would make using this fine piece of software usable for people using file systems and brings the blackhole feature on par with other products like SabNZBd or Transmission.

I might need some pointers where to create/schedule the task and add the configuration vars without creating too much chaos. 

What do you think? Would this be a useful contribution to the project?

Thanks for any help in advance and also thanks for this great application!

### PR DESCRIPTION
**Pull request by gersilex**
Closes #205 

I had to move `MyHandler` class up to make it available as global variable, because both `watchdir` and `walk_watchdir` access the watchdog handler now. I am not sure if this is the right way to implement this. If you have other ideas that fit your code style better, please feel free to make changes or contact me.

Config file needs to be changed for this to work, otherwise it misses the two new options `watchdir_walk_enabled` and `watchdir_walk_interval`.

### CODE REVIEW

**Comment by piejanssens** [comment]
@neox387 Is there a need to increase the settings version or is this good to go?

**Comment by neox387** [comment]
> @neox387 Is there a need to increase the settings version or is this good to go?

Yes, bump to 2.3

**Comment by neox387** [comment]
Could have also used just 1 new config value, the interval

settings.cfg.tpl:
self.watchdir_walk_interval = 0

self.watchdir_walk_interval = prem_config.getint('upload', 'watchdir_walk_interval')
if self.watchdir_walk_interval != 0:
    self.watchdir_walk_enabled = 1

**Comment by gersilex** [comment]
> think it's best to add the job over there else walk_watchdir() might start to early.

Sounds great. And you're right, there is no need to walk the watchdir when starting up immediately, if we can just add_job and have it run a couple of seconds later.

> Could have also used just 1 new config value

Trying to stick to the design concept of the other settings, I added a switch for the feature. I also wouldn't care to remove the switch and use `0` to disable it (and add a `(0 to disable)` info message), through.

**Comment by neox387** [comment]
0 for instant, delay for scan interval (required for network share) or something makes sense =D

But extra toggle for on/off is fine whatever piejanssens wants ^^

**Comment by piejanssens** [comment]
@gersilex If you could implement the suggested changes from @neox387 and bump the config version to 2.3 https://github.com/piejanssens/premiumizer/blob/master/premiumizer/settings.cfg.tpl#L91 and append those commits to this PR, I'll merge.

**Comment by gersilex** [comment]
@piejanssens Done and ready.

@neox387 
> not sure if this github code change is with the right tabs for python =D

It wasn't ^^ Had to fix it.

**Comment by piejanssens** [comment]
Thanks

**Pull request merged**
